/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ugurkellecioglu.sorting;

import static com.ugurkellecioglu.sorting.Controller.myFrame;
import static com.ugurkellecioglu.sorting.Controller.number_of_stick;
import static com.ugurkellecioglu.sorting.Controller.sticks;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author ugur
 */
public class MyFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_wrapper = new javax.swing.JPanel();
        button_create_array = new javax.swing.JButton();
        label_array_count = new javax.swing.JLabel();
        slider_array_count = new javax.swing.JSlider();
        panel_sticks = new MyPanel();
        button_selection_sort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_create_array.setText("Create Array");
        button_create_array.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_create_arrayActionPerformed(evt);
            }
        });

        label_array_count.setText("50");

        slider_array_count.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_array_countStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel_sticksLayout = new javax.swing.GroupLayout(panel_sticks);
        panel_sticks.setLayout(panel_sticksLayout);
        panel_sticksLayout.setHorizontalGroup(
            panel_sticksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );
        panel_sticksLayout.setVerticalGroup(
            panel_sticksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        button_selection_sort.setText("Selection Sort");
        button_selection_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_selection_sortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_wrapperLayout = new javax.swing.GroupLayout(panel_wrapper);
        panel_wrapper.setLayout(panel_wrapperLayout);
        panel_wrapperLayout.setHorizontalGroup(
            panel_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_wrapperLayout.createSequentialGroup()
                        .addComponent(slider_array_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_array_count))
                    .addGroup(panel_wrapperLayout.createSequentialGroup()
                        .addGroup(panel_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_create_array, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(button_selection_sort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addComponent(panel_sticks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        panel_wrapperLayout.setVerticalGroup(
            panel_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slider_array_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_array_count))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_wrapperLayout.createSequentialGroup()
                        .addComponent(button_create_array)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_selection_sort))
                    .addComponent(panel_sticks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_create_arrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_create_arrayActionPerformed
        Controller.number_of_stick = slider_array_count.getValue();
        Controller.createSticks();
    }//GEN-LAST:event_button_create_arrayActionPerformed

    private void slider_array_countStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_array_countStateChanged
      label_array_count.setText(String.valueOf(slider_array_count.getValue()));
    }//GEN-LAST:event_slider_array_countStateChanged

    private void button_selection_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_selection_sortActionPerformed
       Controller.selectionSort();
    }//GEN-LAST:event_button_selection_sortActionPerformed

    public JPanel getPanel_sticks() {
        return panel_sticks;
    }

   

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_create_array;
    private javax.swing.JButton button_selection_sort;
    private javax.swing.JLabel label_array_count;
    private MyPanel panel_sticks;
    private javax.swing.JPanel panel_wrapper;
    private javax.swing.JSlider slider_array_count;
    // End of variables declaration//GEN-END:variables
}
